### ISSUE TITLE
conflicts with vanilla crafting guide (fabric version)

### ISSUE THREAD

**Issue by NotADinosaur** [coolsimulations/EffectsLeft#1]
vanilla behavior (pre 1.18) :  when crafting guide is open, effects disappear
with this mod: potion effect and crafting guide overlap

**Comment by coolsimulations** [comment]
Do you have a screenshot of this issue or any more information? I know sometimes the crafting guide and effects overlap for a split second and there's not much I can do about that. As for when the guide is open and the effects "disappear"... that's how it was pre 1.18 so that's not an issue. The whole point of 1.18 moving the effects to the right is so that you can see the crafting guide at the same time. So most issues regarding the crafting guide don't really apply to this mod as it was intended to be used with JEI/REI (a better version of the crafting guide.)
