### ISSUE TITLE
Unsafe Overwrite mixins

### ISSUE THREAD

**Issue by Darkhax** [coolsimulations/EffectsLeft#2]
The renderBackgrounds and renderIcons mixin use Overwrite which is not a good idea for mod compatibility. Several mods including some of my own mixin the renderBackgrounds method to calculate effect regions on the screen for stuff like tooltips. Overwrites are also a bad idea in general for mod compatibility.

**Comment by coolsimulations** [comment]
Thanks for the info. I had issues with those two particular methods as ModifyArg/s weren't working and caused crashes with no log information. Anyway, I have found the issue (looks like methods in abstract classes can't be used as targets). Now fixed in these two commits https://github.com/coolsimulations/EffectsLeft/commit/45297e8fbf3719b6674966319f9d5a0c505326fa https://github.com/coolsimulations/EffectsLeft/commit/7cacb3ead94c59ac076f5899220bb3ed2f2fe4b2 The update will release when 1.19 comes out.
